### ISSUE TITLE
Release 1 [Powershell] composition

### ISSUE THREAD

**Issue by Nooberking** [Nooberking/UnzipperFileAPI#18]
# Release 1 [Powershell]

## TODO

- [ ] fonction de dézippage de fichier
- [ ] intégration dézippage avec mot de passe
- [ ] choix du lieu de dézippage du fichier
- [ ] envoi du fichier sur OneDrive
