### ISSUE TITLE
Release 1 compostion

### ISSUE THREAD

**Issue by Nooberking** [Nooberking/UnzipperFileAPI#7]
# Release 1

## TODO

- [ ] 1 endpoint pour recevoir le fichier zippé
- [ ] Un lieu de réception du fichier
- [ ] Dézippage et lieu de destination du fichier
- [ ] Renvoi du fichier
